import type { Video } from "@/types";

export const VIDEOS: Video[] = [
  {
    id: "v1",
    title: "5 AM Is a Weapon: Building the Unbreakable Morning",
    platform: "YouTube",
    duration: "8:42",
    thumbnail: "",
    url: "#",
    featured: true,
  },
  {
    id: "v2",
    title: "The Struggle Is the Sharpening Stone",
    platform: "Facebook",
    duration: "3:15",
    thumbnail: "",
    url: "#",
  },
  {
    id: "v3",
    title: "Stop Waiting for Motivation. Build Discipline Instead.",
    platform: "YouTube",
    duration: "11:03",
    thumbnail: "",
    url: "#",
  },
  {
    id: "v4",
    title: "One Rep, One Rejection, One Rise",
    platform: "Shorts",
    duration: "0:47",
    thumbnail: "",
    url: "#",
  },
  {
    id: "v5",
    title: "How Pain Becomes Power",
    platform: "Facebook",
    duration: "4:28",
    thumbnail: "",
    url: "#",
  },
  {
    id: "v6",
    title: "The 1% Rule: Small Wins, Forged Daily",
    platform: "YouTube",
    duration: "9:57",
    thumbnail: "",
    url: "#",
  },
  {
    id: "v7",
    title: "Quit-Proof Your Mindset in 60 Seconds",
    platform: "Shorts",
    duration: "0:59",
    thumbnail: "",
    url: "#",
  },
  {
    id: "v8",
    title: "Real Talk: What Nobody Tells You About Discipline",
    platform: "Facebook",
    duration: "6:11",
    thumbnail: "",
    url: "#",
  },
];
